### ISSUE TITLE
TypeError: rawEmotes is not iterable

### ISSUE THREAD

**Issue by TheLickIn13Keys** [mkody/twitch-emoticons#7]
I really appreciate you providing this library for the community, but I keep running into an error whenever I try to fetch BetterTTV Emotes.

This is my code:
```
  async function getAPIEmote(res, guild){
    return new Promise((resolve, reject) => {
      try{
        fetcher.fetchBTTVEmotes(null).then(() => {
          const foo = fetcher.emotes.get(res);
          if(foo){
            guild.emojis.create(foo.toLink(), res).then(emoji => {
              return resolve(emoji);
            }).catch(console.error);
          }
          else{
            return resolve("NULL");
          }
         
        });

      }catch(err){
        return reject(err);
      }
    });
  }
```

It works perfectly fine when I use fetchTwitchEmotes() tho.

This is the error I'm getting: 

```
[2020-11-29 02:10:49]: ERROR Unhandled rejection: TypeError: rawEmotes is not iterable 
TypeError: rawEmotes is not iterable
    at /home/bardia/Twitch Bot/node_modules/twitch-emoticons-fork/src/struct/EmoteFetcher.js:173:32
    at tryCatcher (/home/bardia/Twitch Bot/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/bardia/Twitch Bot/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/home/bardia/Twitch Bot/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/home/bardia/Twitch Bot/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/home/bardia/Twitch Bot/node_modules/bluebird/js/release/promise.js:729:18)
    at _drainQueueStep (/home/bardia/Twitch Bot/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/home/bardia/Twitch Bot/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/home/bardia/Twitch Bot/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/bardia/Twitch Bot/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (internal/timers.js:456:21)
```
I'm not certain that it is an issue with the library but it seems like it.

Best regards,
Bardia Anvari

**Comment by mkody** [comment]
Sorry for the late reply!

The previous BTTV API was discontinued and might be what made that crash, I've fixed that in https://github.com/mkody/twitch-emoticons/releases/tag/2.3.0
If you could update and give it an another try, to check if it isn't something else I've missed. 😉 

Thanks and best regards
